-- tables
-- table : tweets
CREATE TABLE tweets (
    tweet_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tweet VARCHAR(180) NOT NULL,
    tweet_location VARCHAR(100),
    username VARCHAR(15) NOT NULL UNIQUE,
    tweet_time TIME NOT NULL,
    tweet_date DATE NOT NULL,
    retweet_count INT NOT NULL,
    favorite_count INT NOT NULL,
    user_location VARCHAR(100),
    user_gender VARCHAR(30),
    user_age SMALLINT,
    user_ethnicity VARCHAR(100),
    user_followers INT NOT NULL,
    user_description VARCHAR(160),
    user_join_time TIME NOT NULL,
    user_join_date DATE NOT NULL,
    PRIMARY KEY (tweet_id)
);

-- table :search_queries
CREATE TABLE search_queries (
    query_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    search_query VARCHAR(200) NOT NULL,
    query_time TIME NOT NULL,
    query_date DATE NOT NULL,
    PRIMARY KEY (query_id),
    UNIQUE (query_id, search_query, query_time, query_date)
);

--table : analytics
CREATE TABLE analytics (
    analytic_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    query_id INT references search_queries(query_id) NOT NULL,
    search_query VARCHAR(200) NOT NULL,
    query_time TIME NOT NULL,
    query_date DATE NOT NULL,
    polarity VARCHAR(200) NOT NULL,
    sentiment VARCHAR(200) NOT NULL,
    subjectivity VARCHAR(200) NOT NULL,
    trending_status bool NOT NULL,
    returned_results bool,
    useful_results bool,
    credible_results bool,
    PRIMARY KEY (analytic_id),
    FOREIGN KEY (query_id, search_query, query_time, query_date) REFERENCES search_queries (query_id, search_query, query_time, query_date)
);
